2018-06-26 22:37:37,818 [        MainThread][         start][    INFO] Starting TheRaidMap
2018-06-26 22:37:37,820 [        MainThread][       _legacy][    INFO] Starting factory <client.VNCDoToolFactory instance at 0x111323a70>
2018-06-26 22:37:38,063 [            VNCPic][       _legacy][    INFO] Using protocol version 3.800
2018-06-26 22:37:39,719 [            VNCPic][       _legacy][    INFO] Stopping factory <client.VNCDoToolFactory instance at 0x111323a70>
2018-06-26 22:37:39,719 [            VNCPic][       _legacy][    INFO] Main loop terminated.
2018-06-26 22:37:40,341 [        MainThread][   detect_text][    INFO] Text:O. K.
2018-06-26 22:37:40,342 [        MainThread][   detect_text][    INFO] Loginbutton gefunden
2018-06-26 22:37:50,344 [        MainThread][         start][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "start.py", line 103, in <module>
    main()
  File "start.py", line 67, in main
    check_login()
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/detect_text.py", line 28, in check_login
    clickVNC(750, 340)
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/getVNCPic.py", line 179, in clickVNC
    client1.mouseMove(x, y).mousePress(1)
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/getVNCPic.py", line 105, in proxy_call
    raise TimeoutError("Timeout while waiting for client response")
TimeoutError: Timeout while waiting for client response
