2018-06-26 21:37:47,916 [        MainThread][         start][    INFO] Starting TheRaidMap
2018-06-26 21:37:47,917 [        MainThread][       _legacy][    INFO] Starting factory <client.VNCDoToolFactory instance at 0x1047727e8>
2018-06-26 21:37:48,215 [           Twisted][       _legacy][    INFO] Using protocol version 3.800
2018-06-26 21:37:48,319 [           Twisted][       _legacy][    INFO] Cannot connect password check failed!
2018-06-26 21:37:48,319 [           Twisted][       _legacy][    INFO] Stopping factory <client.VNCDoToolFactory instance at 0x1047727e8>
2018-06-26 21:37:57,920 [        MainThread][         start][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "start.py", line 101, in <module>
    main()
  File "start.py", line 65, in main
    getVNCPic()
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/getVNCPic.py", line 166, in getVNCPic
    client1.captureScreen('screenshot.png')
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/getVNCPic.py", line 105, in proxy_call
    raise TimeoutError("Timeout while waiting for client response")
TimeoutError: Timeout while waiting for client response
