2018-06-26 22:03:34,308 [        MainThread][         start][    INFO] Starting TheRaidMap
2018-06-26 22:03:34,326 [        MainThread][         start][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "start.py", line 103, in <module>
    main()
  File "start.py", line 67, in main
    check_login()
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/detect_text.py", line 16, in check_login
    gray = raidtimer.convert('L')
AttributeError: 'numpy.ndarray' object has no attribute 'convert'
